#!/usr/bin/env bash
# Transfers a file from the client to a server:
# Accepts 4 parameters:
# 1. The path to the file to be transferred
# 2. The IP address of the server
# 3. The username for scp to connect with
# 4. The path to the SSH private key for scp
# Displays Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# if fewer than 4 parameters are passed
# scp transfers the file to the user's home directory ~/
# Strict host key checking is disabled when using scp

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
