#!/usr/bin/env bash
# Displays "To infinity and beyond" endlessly with
# a sleep 2 in between all iteration.
#   Displays "I am invincible!!!" in between all iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
